version: "3.9"
services:
    mongodb:
      image : mongo
      container_name: mongodb
      ports:
        - 27017:27017
      restart: unless-stopped
      environment:
       - MONGO_INITDB_ROOT_USERNAME=${MDB_USERNAME}
       - MONGO_INITDB_ROOT_PASSWORD=${MDB_PASSWORD}
    db:
      container_name: postgres
      image: postgres:14.1
      environment:
        POSTGRES_DB: postgresdb
        POSTGRES_USER: postgresadmin
        POSTGRES_PASSWORD: admin123
      restart: always
      ports:
        - 5432:5432
      volumes:
        - ./_data:/var/lib/postgresql/data
    redis:
     container_name: redis
     image: redis:6.2.6-alpine
     environment:
      - ALLOW_EMPTY_PASSWORD=yes
     ports:
       - 6379:6379
     volumes:
       - ./_data/redis:/data