apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi

---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mypvc
# spec:
#   resources:
#     requests:
#       storage: {2:<Size>}
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
