apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: database
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

