apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-service
  namespace: database
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    # nodePort: 32000
  selector:
    app: mongo
  # type: NodePort
  clusterIP: None
status:
  loadBalancer: {}