apiVersion: v1
kind: Service
metadata:
  name: pg-service
  namespace: database
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  # clusterIP: None
    nodePort: 30001
